{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
apiVersion: {{ include "mywallet.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mywallet.backend.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mywallet.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- if .Values.backend.ingress.tls }}
  tls:
    {{- range .Values.backend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.backend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mywallet.backend.fullname" $ }}
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
